name: base_specCNN_newC_1
#name: test_c_2
DB: /DB/ASVspoof2019/PA/feature/
gpu_idx: [0] #[0, 1]
nb_proc_db: 4
save_dir: /exp/model/networks/
optimizer: Adam #sgd
lr: 0.0005
opt_mom: 0.9
wd: 0.0001
epoch: 100
batch_size: 32
nb_time: 120
feat_dim: 1025
c_loss_weight: 0.00005
c_loss_lr: 0.5

#flags
comet_disable: 0
nesterov: 0 #for sgd optim
amsgrad: 1 #for adam optim
save_best_only: 0


#model-related
model:
  in_channels: 3
  filts: [16, [16, 32], [32, 64], [64, 64], [64, 128], [128, 128]]
  kernels: [[3, 7], [3, 7], [3, 7], [3, 7], [3, 7], [3, 7]]
  strides: [1, 1, [2, 4], [2, 4], [2, 4], [2, 4]]
  blocks: [1, 2, 2, 2]
  nb_fc_node: 64 #4096 #64
  nb_classes: 2
